# Generated by Django 3.2.5 on 2021-07-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Poem')),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('auth', models.CharField(max_length=180, verbose_name='Author')),
                ('my_feeling', models.TextField(verbose_name='My feel')),
            ],
        ),
    ]
