# Generated by Django 3.2.5 on 2021-07-26 08:50

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_PROMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='YOURFEELS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name:')),
                ('y_feels', models.TextField(verbose_name='Your feelings')),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('own_poem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.poem')),
            ],
        ),
    ]
